version: "3"
services:
  api:
      build: ./api
      ports:
          - 8000:8000
      volumes:
          - ./api:/app
      depends_on:
        - postgres

  ui:
    build: ./ui
    volumes:
      - ./ui:/app
    ports:
      - 3000:3000
      - 35729:35729
    
  postgres:
      image: postgres:10-alpine
      environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      volumes:
      - .data/postgres:/var/lib/postgresql/data
      ports:
      - 5432:5432
